name: event_management
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  firebase_database: ^11.1.6
  cached_network_image: ^3.4.1
  sqflite: ^2.0.0+4
  intl_utils: ^2.8.7
  http: ^1.2.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/facebook_logo.png
    - assets/images/gmail_logo.png

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-dir: lib/gen_l10n
