// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ssVAAy33bk5jk-r17-Jlk8DtdOHQBpQ',
    appId: '1:8720837316:web:4219d9fac6b2a0d1e37791',
    messagingSenderId: '8720837316',
    projectId: 'event-management-29368',
    authDomain: 'event-management-29368.firebaseapp.com',
    storageBucket: 'event-management-29368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqb4ze6PhgWvCRa100eOLRLy1qMa1hq1M',
    appId: '1:8720837316:android:2341aaf3f9c0328ae37791',
    messagingSenderId: '8720837316',
    projectId: 'event-management-29368',
    storageBucket: 'event-management-29368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQhts-YwuJnePzkSUyFnttfEYTQ51fCo',
    appId: '1:8720837316:ios:d129db7ba2c5c348e37791',
    messagingSenderId: '8720837316',
    projectId: 'event-management-29368',
    storageBucket: 'event-management-29368.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQhts-YwuJnePzkSUyFnttfEYTQ51fCo',
    appId: '1:8720837316:ios:d129db7ba2c5c348e37791',
    messagingSenderId: '8720837316',
    projectId: 'event-management-29368',
    storageBucket: 'event-management-29368.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ssVAAy33bk5jk-r17-Jlk8DtdOHQBpQ',
    appId: '1:8720837316:web:af84391e43ea176de37791',
    messagingSenderId: '8720837316',
    projectId: 'event-management-29368',
    authDomain: 'event-management-29368.firebaseapp.com',
    storageBucket: 'event-management-29368.firebasestorage.app',
  );

}