name: Flutter CI (Check for Errors)

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  flutter-ci:
    name: Check Flutter Code for Errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test
